### ISSUE TITLE
[FEATURE] Add installation instrutions to the `README.md`

### ISSUE THREAD

**Issue by sschuberth** [cocogitto/cocogitto-bot#18]
**Is your feature request related to a problem? Please describe.**

I'm unsure how to take this project into use in a GitHub project. It does not seem to be a GitHub action, or?

**Describe the solution you'd like**

Please explain in the `README.md` how to take this into use in an existing GitHub project to check PRs for adhering to conventional commits.

**Describe alternatives you've considered**

Researching how other projects might have done it, but that does not scale for new users.

**Comment by sschuberth** [comment]
Ok, I just realized the installation instructions are "hidden" over [here](https://docs.cocogitto.io/ci_cd/#github-bot).

**Comment by oknozor** [comment]
Indeed installation instructions are in the official documentation but I would be nice to also add those to the README
