### ISSUE TITLE
[BUG] Bot not running at PR creation time

### ISSUE THREAD

**Issue by Djaytan** [cocogitto/cocogitto-bot#22]
**Describe the bug**
At PR creation time, I observe everytime that the bot is not dispatched.
![image](https://github.com/cocogitto/cocogitto-bot/assets/26904516/d6801264-a079-4caf-8f22-278b0b6a0be7)

**To Reproduce**
* Simply create a new PR where the Cocogitto bot has been activated
* Check that the bot is not dispatched (no comment nor status check progressing/passing/failing)
* Amend and force push the initial commit should force status checks to be retriggered => Cocogitto bot will provide the status check and the comment this time.

**Expected behavior**
The bot must add a comment in the PR and provide a status check (passing or not depending on whether the Git history is compliant with Conventional Commits or not).

**Additional context**
The bug is observable in the repository: https://github.com/Djaytan/mc-jobs-reborn-patch-place-break
I didn't tried elsewhere yet.

**Comment by Djaytan** [comment]
This bug is not a blocker since a workaround exists. That being said, the impact remains high.

**Comment by Djaytan** [comment]
![image](https://github.com/cocogitto/cocogitto-bot/assets/26904516/7739842c-b92a-4209-a58c-4fe5fe320deb)

**Comment by yoctoyotta1024** [comment]
I and someone else have the exact same problem (see: https://github.com/yoctoyotta1024/CLEO)

Also I think this repository does! (see: https://github.com/cocogitto/cocogitto-bot)

**Comment by oknozor** [comment]
Hey guys, just so you know, I am working on a fix. I just don't have a lot of spare time lately. Thanks for your patience :smiley:

**Comment by oknozor** [comment]
closed by #24
